export enum TypeSkill {
  TOEIC = "TOEIC",
  IELTS = "IELTS",
  TOEFL = "TOEFL",
  PTE = "PTE",
  TOEIC_SPEAKING = "TOEIC_SPEAKING",
  IELTS_SPEAKING = "IELTS_SPEAKING",
  TOEFL_SPEAKING = "TOEFL_SPEAKING",
  PTE_SPEAKING = "PTE_SPEAKING",
}
